image: gitpod/workspace-full:latest

tasks:
  - init: |
      python -m pip install --upgrade pip
      python -m pip install mkdocs
      mkdocs new mkdocs-demo

    command: |
        cd mkdocs-demo
        mkdocs serve
  
ports:
  - port: 8000
    onOpen: open-preview
    
vscode:
   extensions:
     - REditorSupport.r

